version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8000:3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80